/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1f71bc96-94c9-4625-beb4-0bdc3da950f2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_N2FhDCvWR",
    "aws_user_pools_web_client_id": "3kc23nevdrnq65bpm3nqi8uvcd",
    "oauth": {}
};


export default awsmobile;
